### ISSUE TITLE
Add shopping cart icon to top right of page and render a slideout

### ISSUE THREAD

**Issue by ks10825n** [calvincchong/MenuManagement#14]
**What**
Add a shopping cart that users can view

**How**
Create a shopping cart component (slideout).
When user clicks shopping cart icon, display the slideout.

**Acceptance**
User should be able to click on the icon and open a slideout

**Comment by calvincchong** [comment]
How: 

- [ ] make reducer m
- [ ] add reducer to Store reducer/store.js
