### ISSUE TITLE
Ensure shopping cart icon has a count of items

### ISSUE THREAD

**Issue by ks10825n** [calvincchong/MenuManagement#16]
**What**
Shopping cart items should have a count of added items for users to tell how much they have.

**How**
Might need to use CSS to have a number appear on the shopping cart. Display total items in shopping cart.

**Acceptance**
User can tell how many items are in their cart

**Comment by calvincchong** [comment]
Users can tell how many items there are. Currently this is done by having the component check the length of the 'cart' key in localstorage. 

If I change the cart instead to be an array of objects, with itemId, name, price, and quantity, then I will have to change the functionality to sum up the quantity of the objects instead.
